name: github-action-push-branch

on:
  - push
  - pull_request

env: {}

jobs:
  setup:
    name: Setup
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Foo
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
  build:
    name: Build
    runs-on: windows-2022
    needs:
      - setup
    strategy:
      matrix:
        platform:
          - x86
          - x64
        configuration:
          - Debug
          - Release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Foo
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - name: Build
        run: msbuild i343-native-dynamic-library.sln -p:Configuration=${{ matrix.configuration }} -p:Platform=${{ matrix.platform }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.configuration }}-${{ matrix.platform }}
          path: |
            x86/
            x64/
            Debug/
            Release/
      - name: Run Tests
        uses: microsoft-approved-actions/vstest@v1.0.0
        with:
          searchFolder: i343-native-dynamic-library-tests
          codeCoverageEnabled: true
  publish:
    name: Publish
    runs-on: windows-2022
    needs:
      - build
    steps:
      - name: Download Something
        uses: actions/download-artifacts@v3
        with:
          name: Debug-x86
          path: Debug
      - name: Download Something
        uses: actions/download-artifacts@v3
        with:
          name: Release-x86
          path: Release
      - name: Download Something
        uses: actions/download-artifacts@v3
        with:
          name: Debug-x64
          path: x64
      - name: Download Something
        uses: actions/download-artifacts@v3
        with:
          name: Debug-x64
          path: x64
